# Node Build and Validate on Pull Request
# GitHub security update requires pull_request_target to allow secret access
# from external PR's. Label used to ensure vetted first.
name: PullReq CI

on:
  pull_request_target

jobs:
  build:
    name: Build PR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR
        uses: actions/checkout@v2
        with: 
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm ci, run validate
        run: |
          cp .env.sample .env
          npm ci
          npm run validate
        env:
          CI: true
      - name: Slack Notification
        uses: 8398a7/action-slack@v3
        with:
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
          status: ${{ job.status }}
          author_name: PullReq CI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_DEV_NOTIFICATIONS }}
        if: always()
